// Code generated by protoc-gen-go.
// source: bucket.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	bucket.proto
	registry.proto
	types.proto

It has these top-level messages:
	NewItem
	PutSummary
	Key
	Item
	NewBucket
	Bucket
	BucketStatus
	Empty
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// NewItem is used to put an item in a bucket.
type NewItem struct {
	// Item to save in the bucket.
	// @inject_tag: valid:"required"
	Item *Item `protobuf:"bytes,1,opt,name=item" json:"item,omitempty" valid:"required"`
	// Bucket name.
	// @inject_tag: valid:"required"
	Bucket string `protobuf:"bytes,2,opt,name=bucket" json:"bucket,omitempty" valid:"required"`
}

func (m *NewItem) Reset()                    { *m = NewItem{} }
func (m *NewItem) String() string            { return proto1.CompactTextString(m) }
func (*NewItem) ProtoMessage()               {}
func (*NewItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NewItem) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

// PutSummary is received in response to a Put route.
type PutSummary struct {
	// The number of items received.
	ItemCount int32 `protobuf:"varint,1,opt,name=item_count,json=itemCount" json:"item_count,omitempty"`
}

func (m *PutSummary) Reset()                    { *m = PutSummary{} }
func (m *PutSummary) String() string            { return proto1.CompactTextString(m) }
func (*PutSummary) ProtoMessage()               {}
func (*PutSummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Key struct {
	// @inject_tag: valid:"required"
	Bucket string `protobuf:"bytes,1,opt,name=bucket" json:"bucket,omitempty" valid:"required"`
	// @inject_tag: valid:"required"
	Key string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty" valid:"required"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto1.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Item struct {
	// @inject_tag: valid:"required"
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty" valid:"required"`
	// @inject_tag: valid:"required"
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty" valid:"required"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto1.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto1.RegisterType((*NewItem)(nil), "proto.NewItem")
	proto1.RegisterType((*PutSummary)(nil), "proto.PutSummary")
	proto1.RegisterType((*Key)(nil), "proto.Key")
	proto1.RegisterType((*Item)(nil), "proto.Item")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for BucketService service

type BucketServiceClient interface {
	// Put user data
	Put(ctx context.Context, opts ...grpc.CallOption) (BucketService_PutClient, error)
	// Get an item
	Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Item, error)
	// Delete an item
	Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error)
}

type bucketServiceClient struct {
	cc *grpc.ClientConn
}

func NewBucketServiceClient(cc *grpc.ClientConn) BucketServiceClient {
	return &bucketServiceClient{cc}
}

func (c *bucketServiceClient) Put(ctx context.Context, opts ...grpc.CallOption) (BucketService_PutClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BucketService_serviceDesc.Streams[0], c.cc, "/proto.BucketService/Put", opts...)
	if err != nil {
		return nil, err
	}
	x := &bucketServicePutClient{stream}
	return x, nil
}

type BucketService_PutClient interface {
	Send(*NewItem) error
	CloseAndRecv() (*PutSummary, error)
	grpc.ClientStream
}

type bucketServicePutClient struct {
	grpc.ClientStream
}

func (x *bucketServicePutClient) Send(m *NewItem) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bucketServicePutClient) CloseAndRecv() (*PutSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *bucketServiceClient) Get(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := grpc.Invoke(ctx, "/proto.BucketService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bucketServiceClient) Delete(ctx context.Context, in *Key, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/proto.BucketService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BucketService service

type BucketServiceServer interface {
	// Put user data
	Put(BucketService_PutServer) error
	// Get an item
	Get(context.Context, *Key) (*Item, error)
	// Delete an item
	Delete(context.Context, *Key) (*Empty, error)
}

func RegisterBucketServiceServer(s *grpc.Server, srv BucketServiceServer) {
	s.RegisterService(&_BucketService_serviceDesc, srv)
}

func _BucketService_Put_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BucketServiceServer).Put(&bucketServicePutServer{stream})
}

type BucketService_PutServer interface {
	SendAndClose(*PutSummary) error
	Recv() (*NewItem, error)
	grpc.ServerStream
}

type bucketServicePutServer struct {
	grpc.ServerStream
}

func (x *bucketServicePutServer) SendAndClose(m *PutSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bucketServicePutServer) Recv() (*NewItem, error) {
	m := new(NewItem)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BucketService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BucketService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServiceServer).Get(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

func _BucketService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Key)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BucketServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.BucketService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BucketServiceServer).Delete(ctx, req.(*Key))
	}
	return interceptor(ctx, in, info, handler)
}

var _BucketService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.BucketService",
	HandlerType: (*BucketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _BucketService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BucketService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Put",
			Handler:       _BucketService_Put_Handler,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto1.RegisterFile("bucket.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x5d, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0xb3, 0xa6, 0x89, 0x74, 0x12, 0x45, 0x07, 0x91, 0x12, 0x10, 0xc3, 0xe2, 0x43, 0x40,
	0x89, 0x50, 0x6f, 0x50, 0x15, 0x91, 0x82, 0x94, 0xf4, 0x00, 0xd2, 0x86, 0x79, 0x28, 0xed, 0x9a,
	0x10, 0x67, 0x23, 0x7b, 0x00, 0xef, 0x2d, 0xbb, 0x59, 0x34, 0x3e, 0x65, 0xfe, 0x1f, 0xfc, 0x32,
	0xb3, 0x90, 0x6e, 0x75, 0xbd, 0x27, 0x2e, 0xdb, 0xae, 0xe1, 0x06, 0x23, 0xf7, 0xc9, 0x12, 0x36,
	0x2d, 0x7d, 0x0e, 0x9e, 0x5c, 0xc0, 0xf1, 0x1b, 0x7d, 0xbd, 0x32, 0x29, 0xbc, 0x86, 0xc9, 0x8e,
	0x49, 0xcd, 0x44, 0x2e, 0x8a, 0x64, 0x9e, 0x0c, 0x85, 0xd2, 0x46, 0x95, 0x0b, 0xf0, 0x12, 0xe2,
	0x81, 0x37, 0x3b, 0xca, 0x45, 0x31, 0xad, 0xbc, 0x92, 0xb7, 0x00, 0x2b, 0xcd, 0x6b, 0xad, 0xd4,
	0xa6, 0x33, 0x78, 0x05, 0x60, 0xdb, 0xef, 0x75, 0xa3, 0x3f, 0xd8, 0xc1, 0xa2, 0x6a, 0x6a, 0x9d,
	0x47, 0x6b, 0xc8, 0x7b, 0x08, 0x97, 0x64, 0x46, 0x2c, 0x31, 0x66, 0xe1, 0x19, 0x84, 0x7b, 0x32,
	0xfe, 0x07, 0x76, 0x94, 0x25, 0x4c, 0xdc, 0x7a, 0x3e, 0x11, 0xbf, 0x09, 0x5e, 0x40, 0xd4, 0x6f,
	0x0e, 0x9a, 0x5c, 0x3b, 0xad, 0x06, 0x31, 0xff, 0x16, 0x70, 0xb2, 0x70, 0xb0, 0x35, 0x75, 0xfd,
	0xae, 0x26, 0xbc, 0x83, 0x70, 0xa5, 0x19, 0x4f, 0xfd, 0x45, 0xfe, 0xde, 0xec, 0xdc, 0xeb, 0xbf,
	0xdd, 0x65, 0x50, 0x08, 0xcc, 0x21, 0x7c, 0x21, 0x46, 0xf0, 0xe9, 0x92, 0x4c, 0x36, 0x7e, 0x0b,
	0x19, 0xe0, 0x0d, 0xc4, 0x4f, 0x74, 0x20, 0xa6, 0x7f, 0xa5, 0xd4, 0xcf, 0xcf, 0xaa, 0x65, 0x23,
	0x83, 0x6d, 0xec, 0xe4, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xd9, 0x3f, 0xf2, 0x84,
	0x01, 0x00, 0x00,
}
